services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: ghcr.io/acilearning/docker-haskell:9.2.4
    init: true
    volumes:
      - ..:/workspaces/witch
      - cabal:/home/haskell/.cabal
      - cabal-store:/cabal-store
    working_dir: /workspaces/witch
volumes:
  cabal: null
  cabal-store:
    external: true
